import React, { useState } from 'react';
import { ScrollView, StyleSheet, Text, TouchableOpacity, View, Share } from 'react-native';
import { useRouter } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { COLORS, SPACING, FONT_SIZES, RADIUS, SHADOWS } from '../../../lib/theme';

const PHASES = [
  {
    week: 'Days 1–3',
    title: 'Cleanout & Reset',
    color: '#e8f4fd',
    border: '#2196F3',
    steps: [
      { time: 'Morning', action: 'Follow pediatrician\'s cleanout protocol (MiraLax dose as prescribed). Offer extra fluids — water, diluted juice, warm broth.' },
      { time: 'After breakfast', action: '5-minute timed sit on the toilet. No pressure to produce. Feet flat on a stool. Praise for sitting, not for output.' },
      { time: 'After lunch', action: 'Second 5-minute timed sit. Use a visual timer so your child knows when it ends.' },
      { time: 'After dinner', action: 'Third 5-minute timed sit. Keep it calm — no screens, no rushing.' },
      { time: 'Watch for', action: 'Large output, change in stool consistency. Log in Bowel Diary. Contact pediatrician if no output after 48 hours.' },
    ],
  },
  {
    week: 'Days 4–7',
    title: 'Establish the Routine',
    color: '#f0faf5',
    border: '#4CAF50',
    steps: [
      { time: 'Morning sit', action: '5–10 minutes after waking. The gastrocolic reflex is strongest in the morning — use it. Warm drink beforehand can help.' },
      { time: 'After each meal', action: 'Short 5-minute sit within 20 minutes of finishing eating. Consistency matters more than duration.' },
      { time: 'Positioning', action: 'Feet must be supported (Squatty Potty or step stool). Knees above hips. Lean slightly forward. This is the natural squatting position.' },
      { time: 'Reward system', action: 'Reward every sit attempt — not just successful BMs. Sticker chart, token board, or preferred activity works well.' },
      { time: 'Fiber & fluids', action: 'Aim for age + 5 grams of fiber daily. Pears, kiwi, prunes, beans. Keep water intake up — dehydration is the #1 cause of recurrence.' },
    ],
  },
  {
    week: 'Week 2',
    title: 'Build Consistency',
    color: '#fef9e7',
    border: '#FF9800',
    steps: [
      { time: 'Reduce to 2 sits/day', action: 'Morning (after waking) and evening (after dinner). Keep the routine predictable — same time, same place.' },
      { time: 'Fade the timer', action: 'Start letting your child self-regulate the duration. Praise for staying on the toilet without the timer as a prompt.' },
      { time: 'Watch for withholding', action: 'Signs: crossing legs, squatting, standing on tiptoes, hiding in corners. If you see this, go back to 3 sits/day and contact your provider.' },
      { time: 'School coordination', action: 'Send a note to the teacher. Request a bathroom pass. Accidents at school often happen because kids are afraid to ask.' },
      { time: 'Celebrate progress', action: 'Even partial progress counts. 5 accident-free days is a win. Keep the Bowel Diary going — it\'s your evidence for the next provider visit.' },
    ],
  },
  {
    week: 'Week 3–4',
    title: 'Maintenance',
    color: '#fdf0f8',
    border: '#9C27B0',
    steps: [
      { time: 'Continue fiber & fluids', action: 'This is a long-term change, not a short-term fix. Constipation in autistic kids often recurs when diet changes stop.' },
      { time: 'MiraLax taper', action: 'Only reduce MiraLax dose with your pediatrician\'s guidance. Stopping too soon is the most common reason for relapse.' },
      { time: 'Celebrate independence', action: 'If your child is initiating bathroom trips on their own — that\'s huge. Acknowledge it every time.' },
      { time: 'Provider follow-up', action: 'Bring your Bowel Diary to the next appointment. Ask about PFPT (pelvic floor physical therapy) if withholding continues.' },
    ],
  },
];

const POSITIONING_TIPS = [
  { emoji: '🦶', tip: 'Feet flat on a step stool — knees at or above hip level' },
  { emoji: '↗️', tip: 'Lean slightly forward with elbows on knees' },
  { emoji: '💨', tip: 'Breathe out slowly while bearing down — never hold breath' },
  { emoji: '⏱️', tip: 'Use a visual timer — 5 minutes max per sit' },
  { emoji: '🎵', tip: 'Soft music or a preferred audio can reduce anxiety' },
];

export default function BowelRetrainingScreen() {
  const router = useRouter();
  const insets = useSafeAreaInsets();
  const [expandedPhase, setExpandedPhase] = useState<number | null>(0);

  const handleShare = async () => {
    const text = PHASES.map(p =>
      `${p.week}: ${p.title}\n${p.steps.map(s => `• ${s.time}: ${s.action}`).join('\n')}`
    ).join('\n\n');
    await Share.share({
      title: 'Bowel Retraining Schedule — Autism Pathways',
      message: `BOWEL RETRAINING SCHEDULE\nAutism Pathways\n\n${text}\n\nGenerated by Autism Pathways · For personal use only`,
    });
  };

  return (
    <View style={[styles.container, { paddingTop: insets.top }]}>
      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity onPress={() => router.back()} hitSlop={{ top: 16, bottom: 16, left: 16, right: 16 }}>
          <Text style={styles.backText}>← Back</Text>
        </TouchableOpacity>
        <View style={{ alignItems: "center" }}>
          <Text style={styles.headerTitle}>Bowel Retraining</Text>
          <TouchableOpacity onPress={() => router.push("/(tabs)/dashboard")}><Text style={{ fontSize: 10, color: "rgba(255,255,255,0.7)", marginTop: 1 }}>🏠 Dashboard</Text></TouchableOpacity>
        </View>
        <TouchableOpacity onPress={handleShare} style={styles.shareBtn}>
          <Text style={styles.shareBtnText}>Share</Text>
        </TouchableOpacity>
      </View>

      <ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}>
        {/* Intro */}
        <View style={styles.introCard}>
          <Text style={styles.introEmoji}>📋</Text>
          <Text style={styles.introTitle}>Full Bowel Retraining Schedule</Text>
          <Text style={styles.introBody}>
            This 4-week protocol is designed for children with encopresis (chronic constipation with overflow leakage). It works best when started after a medical cleanout prescribed by your pediatrician. Always coordinate with your child's doctor before beginning.
          </Text>
        </View>

        {/* OT Note */}
        <View style={styles.brittanyNote}>
          <Text style={styles.brittanyNoteText}>
            💜 <Text style={{ fontWeight: '700' }}>OT Note:</Text> This protocol will be reviewed and refined by our occupational therapist. Content is based on evidence-based pediatric constipation management guidelines.
          </Text>
        </View>

        {/* Positioning Tips */}
        <Text style={styles.sectionTitle}>Positioning Matters</Text>
        <Text style={styles.sectionSubtitle}>Correct positioning can make the difference between success and struggle. Every sit should use this setup:</Text>
        <View style={styles.positioningCard}>
          {POSITIONING_TIPS.map((t, i) => (
            <View key={i} style={styles.positioningRow}>
              <Text style={styles.positioningEmoji}>{t.emoji}</Text>
              <Text style={styles.positioningText}>{t.tip}</Text>
            </View>
          ))}
        </View>

        {/* Phase Cards */}
        <Text style={styles.sectionTitle}>The 4-Week Protocol</Text>
        {PHASES.map((phase, idx) => (
          <TouchableOpacity
            key={idx}
            style={[styles.phaseCard, { borderLeftColor: phase.border, backgroundColor: phase.color }]}
            onPress={() => setExpandedPhase(expandedPhase === idx ? null : idx)}
            activeOpacity={0.85}
          >
            <View style={styles.phaseHeader}>
              <View>
                <Text style={[styles.phaseWeek, { color: phase.border }]}>{phase.week}</Text>
                <Text style={styles.phaseTitle}>{phase.title}</Text>
              </View>
              <Text style={styles.phaseChevron}>{expandedPhase === idx ? '▲' : '▼'}</Text>
            </View>
            {expandedPhase === idx && (
              <View style={styles.phaseSteps}>
                {phase.steps.map((step, si) => (
                  <View key={si} style={styles.stepRow}>
                    <Text style={[styles.stepTime, { color: phase.border }]}>{step.time}</Text>
                    <Text style={styles.stepAction}>{step.action}</Text>
                  </View>
                ))}
              </View>
            )}
          </TouchableOpacity>
        ))}

        {/* When to call the doctor */}
        <View style={styles.alertCard}>
          <Text style={styles.alertTitle}>🚨 When to Contact Your Pediatrician</Text>
          {[
            'No bowel movement after 48 hours of cleanout',
            'Severe abdominal pain or vomiting',
            'Blood in stool (more than a small streak)',
            'Regression after 2+ weeks of progress',
            'Child is withholding consistently despite the routine',
          ].map((item, i) => (
            <Text key={i} style={styles.alertItem}>• {item}</Text>
          ))}
        </View>

        {/* CTA */}
        <TouchableOpacity style={styles.diaryBtn} onPress={() => router.push('/potty/bowel-diary')}>
          <Text style={styles.diaryBtnText}>📊 Open Bowel Diary to Track Progress</Text>
        </TouchableOpacity>
        <TouchableOpacity style={styles.shareFullBtn} onPress={handleShare}>
          <Text style={styles.shareFullBtnText}>📤 Share This Schedule</Text>
        </TouchableOpacity>

        <Text style={styles.footer}>Autism Pathways · For personal use only · Not a substitute for medical advice</Text>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.bg },
  header: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: SPACING.lg, paddingVertical: SPACING.md,
    borderBottomWidth: 1, borderBottomColor: COLORS.border, backgroundColor: COLORS.bg,
  },
  backText: { fontSize: FONT_SIZES.sm, color: COLORS.purple, fontWeight: '600' },
  headerTitle: { fontSize: FONT_SIZES.md, fontWeight: '700', color: COLORS.text },
  shareBtn: { paddingHorizontal: SPACING.sm, paddingVertical: 4, borderRadius: RADIUS.full, borderWidth: 1, borderColor: COLORS.purple },
  shareBtnText: { fontSize: FONT_SIZES.sm, color: COLORS.purple, fontWeight: '600' },
  scroll: { padding: SPACING.lg, paddingBottom: 48 },
  introCard: {
    backgroundColor: '#f8f4ff', borderRadius: RADIUS.lg, padding: SPACING.lg,
    alignItems: 'center', marginBottom: SPACING.md, ...SHADOWS.card,
  },
  introEmoji: { fontSize: 32, marginBottom: SPACING.sm },
  introTitle: { fontSize: FONT_SIZES.lg, fontWeight: '800', color: COLORS.purple, textAlign: 'center', marginBottom: SPACING.sm },
  introBody: { fontSize: FONT_SIZES.sm, color: COLORS.textSecondary, textAlign: 'center', lineHeight: 20 },
  brittanyNote: {
    backgroundColor: '#fdf4ff', borderRadius: RADIUS.md, padding: SPACING.md,
    borderLeftWidth: 3, borderLeftColor: COLORS.purple, marginBottom: SPACING.lg,
  },
  brittanyNoteText: { fontSize: FONT_SIZES.sm, color: '#5a3e8c', lineHeight: 18 },
  sectionTitle: { fontSize: FONT_SIZES.md, fontWeight: '800', color: COLORS.text, marginBottom: SPACING.xs, marginTop: SPACING.sm },
  sectionSubtitle: { fontSize: FONT_SIZES.sm, color: COLORS.textSecondary, marginBottom: SPACING.md, lineHeight: 18 },
  positioningCard: {
    backgroundColor: '#fff', borderRadius: RADIUS.lg, padding: SPACING.md,
    marginBottom: SPACING.lg, ...SHADOWS.card,
  },
  positioningRow: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: SPACING.sm },
  positioningEmoji: { fontSize: 18, marginRight: SPACING.sm, width: 28 },
  positioningText: { flex: 1, fontSize: FONT_SIZES.sm, color: COLORS.text, lineHeight: 18 },
  phaseCard: {
    borderRadius: RADIUS.lg, borderLeftWidth: 4, padding: SPACING.md,
    marginBottom: SPACING.md, ...SHADOWS.card,
  },
  phaseHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  phaseWeek: { fontSize: FONT_SIZES.xs, fontWeight: '700', letterSpacing: 0.5, textTransform: 'uppercase', marginBottom: 2 },
  phaseTitle: { fontSize: FONT_SIZES.md, fontWeight: '700', color: COLORS.text },
  phaseChevron: { fontSize: 12, color: COLORS.textSecondary },
  phaseSteps: { marginTop: SPACING.md, borderTopWidth: 1, borderTopColor: 'rgba(0,0,0,0.08)', paddingTop: SPACING.md },
  stepRow: { marginBottom: SPACING.md },
  stepTime: { fontSize: FONT_SIZES.xs, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 2 },
  stepAction: { fontSize: FONT_SIZES.sm, color: COLORS.text, lineHeight: 20 },
  alertCard: {
    backgroundColor: '#fff5f5', borderRadius: RADIUS.lg, padding: SPACING.md,
    borderLeftWidth: 4, borderLeftColor: '#e53e3e', marginBottom: SPACING.lg,
  },
  alertTitle: { fontSize: FONT_SIZES.md, fontWeight: '700', color: '#c53030', marginBottom: SPACING.sm },
  alertItem: { fontSize: FONT_SIZES.sm, color: '#742a2a', lineHeight: 22, marginBottom: 2 },
  diaryBtn: {
    backgroundColor: COLORS.purple, borderRadius: RADIUS.full, paddingVertical: 14,
    alignItems: 'center', marginBottom: SPACING.md,
  },
  diaryBtnText: { color: '#fff', fontWeight: '700', fontSize: FONT_SIZES.md },
  shareFullBtn: {
    backgroundColor: '#fff', borderRadius: RADIUS.full, paddingVertical: 14,
    alignItems: 'center', marginBottom: SPACING.lg, borderWidth: 1.5, borderColor: COLORS.purple,
  },
  shareFullBtnText: { color: COLORS.purple, fontWeight: '700', fontSize: FONT_SIZES.md },
  footer: { fontSize: FONT_SIZES.xs, color: COLORS.textSecondary, textAlign: 'center', marginTop: SPACING.sm },
});
