import React, { useState, useEffect } from 'react';
import { ScrollView, StyleSheet, Text, TouchableOpacity, View, Share, TextInput } from 'react-native';
import { useRouter } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { COLORS, SPACING, FONT_SIZES, RADIUS, SHADOWS } from '../../../lib/theme';

const PLAN_KEY = 'ap_potty_school_bathroom_plan';

export default function SchoolBathroomPlanScreen() {
  const router = useRouter();
  const insets = useSafeAreaInsets();
  const [childName, setChildName] = useState('');
  const [teacherName, setTeacherName] = useState('');
  const [grade, setGrade] = useState('');
  const [scheduledTimes, setScheduledTimes] = useState('After lunch, before recess, before dismissal');
  const [signalMethod, setSignalMethod] = useState('');
  const [bathroomLocation, setBathroomLocation] = useState('');
  const [accompaniment, setAccompaniment] = useState('');
  const [accidentProtocol, setAccidentProtocol] = useState('');
  const [additionalNotes, setAdditionalNotes] = useState('');
  const [saved, setSaved] = useState(false);

  useEffect(() => {
    AsyncStorage.getItem(PLAN_KEY).then(val => {
      if (val) {
        const d = JSON.parse(val);
        setChildName(d.childName || '');
        setTeacherName(d.teacherName || '');
        setGrade(d.grade || '');
        setScheduledTimes(d.scheduledTimes || 'After lunch, before recess, before dismissal');
        setSignalMethod(d.signalMethod || '');
        setBathroomLocation(d.bathroomLocation || '');
        setAccompaniment(d.accompaniment || '');
        setAccidentProtocol(d.accidentProtocol || '');
        setAdditionalNotes(d.additionalNotes || '');
      }
    });
  }, []);

  const handleSave = async () => {
    await AsyncStorage.setItem(PLAN_KEY, JSON.stringify({
      childName, teacherName, grade, scheduledTimes, signalMethod,
      bathroomLocation, accompaniment, accidentProtocol, additionalNotes,
    }));
    setSaved(true);
  };

  const handleShare = async () => {
    const text = `SCHOOL BATHROOM SUPPORT PLAN
${childName ? `Student: ${childName}` : ''}${grade ? ` | Grade: ${grade}` : ''}${teacherName ? `\nTeacher: ${teacherName}` : ''}

SCHEDULED BATHROOM TIMES
${scheduledTimes || '[Not specified]'}

HOW THE STUDENT SIGNALS BATHROOM NEED
${signalMethod || '[Not specified]'}

BATHROOM LOCATION
${bathroomLocation || '[Not specified]'}

ACCOMPANIMENT / SUPERVISION
${accompaniment || '[Not specified]'}

ACCIDENT PROTOCOL
${accidentProtocol || '[Not specified]'}

ADDITIONAL NOTES
${additionalNotes || '[None]'}

Generated by Autism Pathways · For school use only`;
    await Share.share({ title: 'School Bathroom Support Plan', message: text });
  };

  return (
    <View style={[styles.container, { paddingTop: insets.top }]}>
      <View style={styles.header}>
        <TouchableOpacity onPress={() => router.back()} hitSlop={{ top: 16, bottom: 16, left: 16, right: 16 }}>
          <Text style={styles.backText}>← Back</Text>
        </TouchableOpacity>
        <View style={{ alignItems: "center" }}>
          <Text style={styles.headerTitle}>School Bathroom Plan</Text>
          <TouchableOpacity onPress={() => router.push("/(tabs)/dashboard")}><Text style={{ fontSize: 10, color: "rgba(255,255,255,0.7)", marginTop: 1 }}>🏠 Dashboard</Text></TouchableOpacity>
        </View>
        <TouchableOpacity onPress={handleShare} style={styles.shareBtn}>
          <Text style={styles.shareBtnText}>Share</Text>
        </TouchableOpacity>
      </View>

      <ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false} keyboardShouldPersistTaps="handled">
        <View style={styles.introCard}>
          <Text style={styles.introEmoji}>🏫</Text>
          <Text style={styles.introTitle}>School Bathroom Support Plan</Text>
          <Text style={styles.introBody}>
            Fill out this plan and share it directly with your child's teacher or aide. It covers scheduled times, signaling methods, accident protocols, and privacy needs — everything the school needs to support your child consistently.
          </Text>
        </View>

        <Text style={styles.sectionTitle}>Student Information</Text>
        <View style={styles.card}>
          <Text style={styles.fieldLabel}>Child's Name</Text>
          <TextInput style={styles.input} value={childName} onChangeText={t => { setChildName(t); setSaved(false); }} placeholder="First name or nickname" placeholderTextColor={COLORS.textSecondary} />
          <Text style={styles.fieldLabel}>Teacher / Aide Name</Text>
          <TextInput style={styles.input} value={teacherName} onChangeText={t => { setTeacherName(t); setSaved(false); }} placeholder="Teacher's name" placeholderTextColor={COLORS.textSecondary} />
          <Text style={styles.fieldLabel}>Grade / Class</Text>
          <TextInput style={styles.input} value={grade} onChangeText={t => { setGrade(t); setSaved(false); }} placeholder="e.g., 2nd grade, Room 14" placeholderTextColor={COLORS.textSecondary} />
        </View>

        <Text style={styles.sectionTitle}>Scheduled Bathroom Times</Text>
        <View style={styles.card}>
          <Text style={styles.fieldHint}>List the specific times during the school day when the student should be prompted to try the bathroom:</Text>
          <TextInput
            style={[styles.input, styles.multiline]}
            value={scheduledTimes}
            onChangeText={t => { setScheduledTimes(t); setSaved(false); }}
            placeholder="e.g., After arrival, after lunch, before recess, before dismissal"
            placeholderTextColor={COLORS.textSecondary}
            multiline
            numberOfLines={3}
          />
        </View>

        <Text style={styles.sectionTitle}>How the Student Signals Bathroom Need</Text>
        <View style={styles.card}>
          <Text style={styles.fieldHint}>Describe how your child communicates that they need to use the bathroom (verbal, AAC device, card, sign, etc.):</Text>
          <TextInput
            style={[styles.input, styles.multiline]}
            value={signalMethod}
            onChangeText={t => { setSignalMethod(t); setSaved(false); }}
            placeholder="e.g., Shows bathroom picture card, says 'bathroom', uses AAC device"
            placeholderTextColor={COLORS.textSecondary}
            multiline
            numberOfLines={3}
          />
          <View style={styles.examplesBox}>
            <Text style={styles.examplesTitle}>Common signal methods:</Text>
            {['Picture/symbol card exchange (PECS)', 'AAC device or app', 'Verbal request (may be unclear — describe what it sounds like)', 'Sign language (describe the sign)', 'Hand gesture or pointing', 'Behavior cues (restlessness, hand-in-pants)'].map((ex, i) => (
              <Text key={i} style={styles.examplesItem}>• {ex}</Text>
            ))}
          </View>
        </View>

        <Text style={styles.sectionTitle}>Bathroom Location & Privacy</Text>
        <View style={styles.card}>
          <Text style={styles.fieldHint}>Which bathroom should the student use? Are there any privacy or sensory accommodations needed?</Text>
          <TextInput
            style={[styles.input, styles.multiline]}
            value={bathroomLocation}
            onChangeText={t => { setBathroomLocation(t); setSaved(false); }}
            placeholder="e.g., Single-occupancy bathroom near the classroom. Needs lights dimmed. Cannot use the main hallway bathroom due to noise."
            placeholderTextColor={COLORS.textSecondary}
            multiline
            numberOfLines={3}
          />
        </View>

        <Text style={styles.sectionTitle}>Accompaniment & Supervision</Text>
        <View style={styles.card}>
          <Text style={styles.fieldHint}>Does the student need an adult to accompany them? What level of support is needed inside the bathroom?</Text>
          <TextInput
            style={[styles.input, styles.multiline]}
            value={accompaniment}
            onChangeText={t => { setAccompaniment(t); setSaved(false); }}
            placeholder="e.g., Needs aide to walk with them and wait outside. Can manage independently once inside. Do not rush — allow 5 minutes."
            placeholderTextColor={COLORS.textSecondary}
            multiline
            numberOfLines={3}
          />
        </View>

        <Text style={styles.sectionTitle}>Accident Protocol</Text>
        <View style={styles.card}>
          <Text style={styles.fieldHint}>What should staff do if the student has an accident? Where are the supplies? How should they respond emotionally?</Text>
          <TextInput
            style={[styles.input, styles.multiline]}
            value={accidentProtocol}
            onChangeText={t => { setAccidentProtocol(t); setSaved(false); }}
            placeholder="e.g., Change of clothes in backpack. Handle calmly and privately — no negative reactions. Notify parent via app message (not phone call during school day)."
            placeholderTextColor={COLORS.textSecondary}
            multiline
            numberOfLines={4}
          />
        </View>

        <Text style={styles.sectionTitle}>Additional Notes</Text>
        <View style={styles.card}>
          <TextInput
            style={[styles.input, styles.multiline]}
            value={additionalNotes}
            onChangeText={t => { setAdditionalNotes(t); setSaved(false); }}
            placeholder="Any other information the school should know..."
            placeholderTextColor={COLORS.textSecondary}
            multiline
            numberOfLines={3}
          />
        </View>

        <TouchableOpacity style={styles.saveBtn} onPress={handleSave}>
          <Text style={styles.saveBtnText}>{saved ? '✓ Saved!' : '💾 Save Plan'}</Text>
        </TouchableOpacity>
        <TouchableOpacity style={styles.shareFullBtn} onPress={handleShare}>
          <Text style={styles.shareFullBtnText}>📤 Share with School</Text>
        </TouchableOpacity>

        <Text style={styles.footer}>Autism Pathways · For school use only</Text>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.bg },
  header: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: SPACING.lg, paddingVertical: SPACING.md,
    borderBottomWidth: 1, borderBottomColor: COLORS.border, backgroundColor: COLORS.bg,
  },
  backText: { fontSize: FONT_SIZES.sm, color: COLORS.purple, fontWeight: '600' },
  headerTitle: { fontSize: FONT_SIZES.md, fontWeight: '700', color: COLORS.text },
  shareBtn: { paddingHorizontal: SPACING.sm, paddingVertical: 4, borderRadius: RADIUS.full, borderWidth: 1, borderColor: COLORS.purple },
  shareBtnText: { fontSize: FONT_SIZES.sm, color: COLORS.purple, fontWeight: '600' },
  scroll: { padding: SPACING.lg, paddingBottom: 48 },
  introCard: {
    backgroundColor: '#f8f4ff', borderRadius: RADIUS.lg, padding: SPACING.lg,
    alignItems: 'center', marginBottom: SPACING.lg, ...SHADOWS.card,
  },
  introEmoji: { fontSize: 32, marginBottom: SPACING.sm },
  introTitle: { fontSize: FONT_SIZES.lg, fontWeight: '800', color: COLORS.purple, textAlign: 'center', marginBottom: SPACING.sm },
  introBody: { fontSize: FONT_SIZES.sm, color: COLORS.textSecondary, textAlign: 'center', lineHeight: 20 },
  sectionTitle: { fontSize: FONT_SIZES.md, fontWeight: '800', color: COLORS.text, marginBottom: SPACING.sm, marginTop: SPACING.sm },
  card: { backgroundColor: '#fff', borderRadius: RADIUS.lg, padding: SPACING.md, marginBottom: SPACING.md, ...SHADOWS.card },
  fieldLabel: { fontSize: FONT_SIZES.xs, fontWeight: '700', color: COLORS.purple, textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 4, marginTop: SPACING.sm },
  fieldHint: { fontSize: FONT_SIZES.sm, color: COLORS.textSecondary, lineHeight: 18, marginBottom: SPACING.sm },
  input: {
    borderWidth: 1.5, borderColor: COLORS.border, borderRadius: RADIUS.md,
    padding: SPACING.sm, fontSize: FONT_SIZES.sm, color: COLORS.text,
    backgroundColor: '#fafafa', marginBottom: SPACING.sm,
  },
  multiline: { minHeight: 80, textAlignVertical: 'top' },
  examplesBox: { backgroundColor: '#f8f4ff', borderRadius: RADIUS.md, padding: SPACING.sm, marginTop: SPACING.xs },
  examplesTitle: { fontSize: FONT_SIZES.xs, fontWeight: '700', color: COLORS.purple, marginBottom: 4 },
  examplesItem: { fontSize: FONT_SIZES.xs, color: COLORS.textSecondary, lineHeight: 18 },
  saveBtn: {
    backgroundColor: COLORS.purple, borderRadius: RADIUS.full, paddingVertical: 14,
    alignItems: 'center', marginBottom: SPACING.md,
  },
  saveBtnText: { color: '#fff', fontWeight: '700', fontSize: FONT_SIZES.md },
  shareFullBtn: {
    backgroundColor: '#fff', borderRadius: RADIUS.full, paddingVertical: 14,
    alignItems: 'center', marginBottom: SPACING.lg, borderWidth: 1.5, borderColor: COLORS.purple,
  },
  shareFullBtnText: { color: COLORS.purple, fontWeight: '700', fontSize: FONT_SIZES.md },
  footer: { fontSize: FONT_SIZES.xs, color: COLORS.textSecondary, textAlign: 'center' },
});
