import React, { useState, useEffect } from 'react';
import { ScrollView, StyleSheet, Text, TouchableOpacity, View, Share, Alert } from 'react-native';
import { useRouter } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { COLORS, SPACING, FONT_SIZES, RADIUS, SHADOWS } from '../../../lib/theme';

const SCHEDULE_KEY = 'ap_potty_visual_schedule';

const STEP_OPTIONS = [
  { id: 'walk', emoji: '🚶', label: 'Walk to bathroom' },
  { id: 'knock', emoji: '🚪', label: 'Knock / check if free' },
  { id: 'close', emoji: '🔒', label: 'Close the door' },
  { id: 'pants-down', emoji: '👖', label: 'Pull pants down' },
  { id: 'sit', emoji: '🪑', label: 'Sit on toilet' },
  { id: 'feet', emoji: '🦶', label: 'Put feet on stool' },
  { id: 'breathe', emoji: '🌬️', label: 'Take a deep breath' },
  { id: 'wait', emoji: '⏱️', label: 'Wait (use timer)' },
  { id: 'try', emoji: '💪', label: 'Try to go' },
  { id: 'wipe', emoji: '🧻', label: 'Wipe (front to back)' },
  { id: 'pants-up', emoji: '👖', label: 'Pull pants up' },
  { id: 'flush', emoji: '🚽', label: 'Flush' },
  { id: 'wash', emoji: '🧼', label: 'Wash hands' },
  { id: 'dry', emoji: '🖐️', label: 'Dry hands' },
  { id: 'reward', emoji: '⭐', label: 'Get reward / sticker' },
];

const TIMING_OPTIONS = ['After waking up', 'After breakfast', 'After lunch', 'After dinner', 'Before bath', 'Before bed', 'Every 2 hours', 'Custom'];

export default function VisualScheduleScreen() {
  const router = useRouter();
  const insets = useSafeAreaInsets();
  const [selectedSteps, setSelectedSteps] = useState<string[]>([
    'walk', 'pants-down', 'sit', 'feet', 'breathe', 'wait', 'wipe', 'pants-up', 'flush', 'wash', 'dry',
  ]);
  const [selectedTimes, setSelectedTimes] = useState<string[]>(['After breakfast', 'After lunch', 'After dinner']);
  const [saved, setSaved] = useState(false);

  useEffect(() => {
    AsyncStorage.getItem(SCHEDULE_KEY).then(val => {
      if (val) {
        const parsed = JSON.parse(val);
        if (parsed.steps) setSelectedSteps(parsed.steps);
        if (parsed.times) setSelectedTimes(parsed.times);
      }
    });
  }, []);

  const toggleStep = (id: string) => {
    setSelectedSteps(prev =>
      prev.includes(id) ? prev.filter(s => s !== id) : [...prev, id]
    );
    setSaved(false);
  };

  const toggleTime = (t: string) => {
    setSelectedTimes(prev =>
      prev.includes(t) ? prev.filter(x => x !== t) : [...prev, t]
    );
    setSaved(false);
  };

  const handleSave = async () => {
    await AsyncStorage.setItem(SCHEDULE_KEY, JSON.stringify({ steps: selectedSteps, times: selectedTimes }));
    setSaved(true);
    Alert.alert('Saved!', 'Your visual schedule has been saved.');
  };

  const handleShare = async () => {
    const steps = selectedSteps.map(id => STEP_OPTIONS.find(s => s.id === id)).filter(Boolean);
    const times = selectedTimes.join(', ');
    const text = `BATHROOM VISUAL SCHEDULE\n\nScheduled times: ${times}\n\nSteps:\n${steps.map((s, i) => `${i + 1}. ${s!.emoji} ${s!.label}`).join('\n')}\n\nGenerated by Autism Pathways`;
    await Share.share({ title: 'Bathroom Visual Schedule', message: text });
  };

  const orderedSteps = selectedSteps
    .map(id => STEP_OPTIONS.find(s => s.id === id))
    .filter(Boolean) as typeof STEP_OPTIONS;

  return (
    <View style={[styles.container, { paddingTop: insets.top }]}>
      <View style={styles.header}>
        <TouchableOpacity onPress={() => router.back()} hitSlop={{ top: 16, bottom: 16, left: 16, right: 16 }}>
          <Text style={styles.backText}>← Back</Text>
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Visual Schedule</Text>
        <TouchableOpacity onPress={handleShare} style={styles.shareBtn}>
          <Text style={styles.shareBtnText}>Share</Text>
        </TouchableOpacity>
      </View>

      <ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}>
        <View style={styles.introCard}>
          <Text style={styles.introEmoji}>🖼️</Text>
          <Text style={styles.introTitle}>Bathroom Visual Schedule Builder</Text>
          <Text style={styles.introBody}>
            Build a custom step-by-step bathroom routine for your child. Select the steps that apply to your child's routine and the times you want them to try. Then share or print it to post in the bathroom.
          </Text>
        </View>

        {/* Schedule Times */}
        <Text style={styles.sectionTitle}>When to Try</Text>
        <Text style={styles.sectionSubtitle}>Select all times that apply to your child's schedule:</Text>
        <View style={styles.chipGrid}>
          {TIMING_OPTIONS.map(t => (
            <TouchableOpacity
              key={t}
              style={[styles.chip, selectedTimes.includes(t) && styles.chipSelected]}
              onPress={() => toggleTime(t)}
            >
              <Text style={[styles.chipText, selectedTimes.includes(t) && styles.chipTextSelected]}>{t}</Text>
            </TouchableOpacity>
          ))}
        </View>

        {/* Step Selector */}
        <Text style={styles.sectionTitle}>Bathroom Steps</Text>
        <Text style={styles.sectionSubtitle}>Tap to add or remove steps. Drag to reorder (coming soon):</Text>
        <View style={styles.stepGrid}>
          {STEP_OPTIONS.map(step => (
            <TouchableOpacity
              key={step.id}
              style={[styles.stepChip, selectedSteps.includes(step.id) && styles.stepChipSelected]}
              onPress={() => toggleStep(step.id)}
            >
              <Text style={styles.stepChipEmoji}>{step.emoji}</Text>
              <Text style={[styles.stepChipLabel, selectedSteps.includes(step.id) && styles.stepChipLabelSelected]}>
                {step.label}
              </Text>
              {selectedSteps.includes(step.id) && <Text style={styles.stepChipCheck}>✓</Text>}
            </TouchableOpacity>
          ))}
        </View>

        {/* Preview */}
        {orderedSteps.length > 0 && (
          <>
            <Text style={styles.sectionTitle}>Preview</Text>
            <Text style={styles.sectionSubtitle}>This is how the schedule will appear when shared or printed:</Text>
            <View style={styles.previewCard}>
              <Text style={styles.previewTitle}>🚽 Bathroom Time!</Text>
              {selectedTimes.length > 0 && (
                <Text style={styles.previewTimes}>⏰ {selectedTimes.join(' · ')}</Text>
              )}
              {orderedSteps.map((step, i) => (
                <View key={step.id} style={styles.previewStep}>
                  <View style={styles.previewNum}>
                    <Text style={styles.previewNumText}>{i + 1}</Text>
                  </View>
                  <Text style={styles.previewEmoji}>{step.emoji}</Text>
                  <Text style={styles.previewLabel}>{step.label}</Text>
                </View>
              ))}
              <Text style={styles.previewFooter}>Great job! 🌟</Text>
            </View>
          </>
        )}

        <TouchableOpacity style={styles.saveBtn} onPress={handleSave}>
          <Text style={styles.saveBtnText}>{saved ? '✓ Saved!' : '💾 Save Schedule'}</Text>
        </TouchableOpacity>
        <TouchableOpacity style={styles.shareFullBtn} onPress={handleShare}>
          <Text style={styles.shareFullBtnText}>📤 Share / Print Schedule</Text>
        </TouchableOpacity>

        <Text style={styles.footer}>Autism Pathways · For personal use only</Text>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.bg },
  header: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: SPACING.lg, paddingVertical: SPACING.md,
    borderBottomWidth: 1, borderBottomColor: COLORS.border, backgroundColor: COLORS.bg,
  },
  backText: { fontSize: FONT_SIZES.sm, color: COLORS.purple, fontWeight: '600' },
  headerTitle: { fontSize: FONT_SIZES.md, fontWeight: '700', color: COLORS.text },
  shareBtn: { paddingHorizontal: SPACING.sm, paddingVertical: 4, borderRadius: RADIUS.full, borderWidth: 1, borderColor: COLORS.purple },
  shareBtnText: { fontSize: FONT_SIZES.sm, color: COLORS.purple, fontWeight: '600' },
  scroll: { padding: SPACING.lg, paddingBottom: 48 },
  introCard: {
    backgroundColor: '#f8f4ff', borderRadius: RADIUS.lg, padding: SPACING.lg,
    alignItems: 'center', marginBottom: SPACING.lg, ...SHADOWS.card,
  },
  introEmoji: { fontSize: 32, marginBottom: SPACING.sm },
  introTitle: { fontSize: FONT_SIZES.lg, fontWeight: '800', color: COLORS.purple, textAlign: 'center', marginBottom: SPACING.sm },
  introBody: { fontSize: FONT_SIZES.sm, color: COLORS.textSecondary, textAlign: 'center', lineHeight: 20 },
  sectionTitle: { fontSize: FONT_SIZES.md, fontWeight: '800', color: COLORS.text, marginBottom: SPACING.xs, marginTop: SPACING.sm },
  sectionSubtitle: { fontSize: FONT_SIZES.sm, color: COLORS.textSecondary, marginBottom: SPACING.md, lineHeight: 18 },
  chipGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: SPACING.lg },
  chip: {
    paddingHorizontal: SPACING.md, paddingVertical: 8, borderRadius: RADIUS.full,
    borderWidth: 1.5, borderColor: COLORS.border, backgroundColor: '#fff',
  },
  chipSelected: { borderColor: COLORS.purple, backgroundColor: '#f0ebff' },
  chipText: { fontSize: FONT_SIZES.sm, color: COLORS.textSecondary, fontWeight: '500' },
  chipTextSelected: { color: COLORS.purple, fontWeight: '700' },
  stepGrid: { gap: 8, marginBottom: SPACING.lg },
  stepChip: {
    flexDirection: 'row', alignItems: 'center', padding: SPACING.sm,
    borderRadius: RADIUS.md, borderWidth: 1.5, borderColor: COLORS.border,
    backgroundColor: '#fff', ...SHADOWS.card,
  },
  stepChipSelected: { borderColor: COLORS.purple, backgroundColor: '#f0ebff' },
  stepChipEmoji: { fontSize: 20, marginRight: SPACING.sm },
  stepChipLabel: { flex: 1, fontSize: FONT_SIZES.sm, color: COLORS.text },
  stepChipLabelSelected: { color: COLORS.purple, fontWeight: '600' },
  stepChipCheck: { fontSize: 14, color: COLORS.purple, fontWeight: '700' },
  previewCard: {
    backgroundColor: '#fff', borderRadius: RADIUS.lg, padding: SPACING.lg,
    marginBottom: SPACING.lg, ...SHADOWS.card, borderWidth: 2, borderColor: COLORS.purple,
  },
  previewTitle: { fontSize: FONT_SIZES.lg, fontWeight: '800', color: COLORS.purple, textAlign: 'center', marginBottom: SPACING.xs },
  previewTimes: { fontSize: FONT_SIZES.xs, color: COLORS.textSecondary, textAlign: 'center', marginBottom: SPACING.md },
  previewStep: { flexDirection: 'row', alignItems: 'center', marginBottom: SPACING.sm },
  previewNum: {
    width: 28, height: 28, borderRadius: 14, backgroundColor: COLORS.purple,
    alignItems: 'center', justifyContent: 'center', marginRight: SPACING.sm,
  },
  previewNumText: { color: '#fff', fontWeight: '700', fontSize: FONT_SIZES.sm },
  previewEmoji: { fontSize: 20, marginRight: SPACING.sm },
  previewLabel: { flex: 1, fontSize: FONT_SIZES.md, color: COLORS.text, fontWeight: '500' },
  previewFooter: { fontSize: FONT_SIZES.md, textAlign: 'center', marginTop: SPACING.md, fontWeight: '700', color: '#e67e22' },
  saveBtn: {
    backgroundColor: COLORS.purple, borderRadius: RADIUS.full, paddingVertical: 14,
    alignItems: 'center', marginBottom: SPACING.md,
  },
  saveBtnText: { color: '#fff', fontWeight: '700', fontSize: FONT_SIZES.md },
  shareFullBtn: {
    backgroundColor: '#fff', borderRadius: RADIUS.full, paddingVertical: 14,
    alignItems: 'center', marginBottom: SPACING.lg, borderWidth: 1.5, borderColor: COLORS.purple,
  },
  shareFullBtnText: { color: COLORS.purple, fontWeight: '700', fontSize: FONT_SIZES.md },
  footer: { fontSize: FONT_SIZES.xs, color: COLORS.textSecondary, textAlign: 'center' },
});
