import React, { useState, useCallback } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { useIsPremium } from '../../hooks/useIsPremium';
import {
  View, Text, StyleSheet, ScrollView, TouchableOpacity,
  TextInput, Linking, Share, Platform,
} from 'react-native';
import { useRouter } from 'expo-router';
import { COLORS, FONT_SIZES, SPACING } from '../../lib/theme';
import { searchDistricts, type SchoolDistrictState } from '../../data/school-districts';

const US_STATES = [
  'AL','AK','AZ','AR','CA','CO','CT','DE','DC','FL','GA','HI','ID','IL','IN',
  'IA','KS','KY','LA','ME','MD','MA','MI','MN','MS','MO','MT','NE','NV','NH',
  'NJ','NM','NY','NC','ND','OH','OK','OR','PA','RI','SC','SD','TN','TX','UT',
  'VT','VA','WA','WV','WI','WY',
];

const DISTRICT_LOOKUP_KEY = 'ap_iep_district_lookup_count';
const FREE_LOOKUPS = 1;

export default function DistrictLookupScreen() {
  const router = useRouter();
  const [query, setQuery] = useState('');
  const [selected, setSelected] = useState<SchoolDistrictState | null>(null);
  const [expandedSection, setExpandedSection] = useState<string | null>('timelines');

  const results = searchDistricts(query);

  const handleSelect = useCallback((district: SchoolDistrictState) => {
    setSelected(district);
    setExpandedSection('timelines');
  }, []);

  const handleShare = useCallback(async () => {
    if (!selected) return;
    const text = `School Evaluation Rights — ${selected.state}\n\n` +
      `State Education Agency: ${selected.seaName}\n` +
      `Phone: ${selected.seaPhone}\n` +
      `Website: ${selected.seaUrl}\n\n` +
      `Evaluation Timeline: ${selected.evaluationTimeline}\n` +
      `Total Timeline: ${selected.totalTimeline}\n\n` +
      `How to Request:\n${selected.howToRequest}\n\n` +
      `Parent Advocacy Resource:\n${selected.escalationContact}\n${selected.escalationUrl}\n\n` +
      `Generated by Autism Pathways`;
    await Share.share({ message: text });
  }, [selected]);

  const toggleSection = (key: string) => {
    setExpandedSection(prev => (prev === key ? null : key));
  };

  const teleheathColor = (val: string) => {
    if (val === 'yes') return COLORS.successText;
    if (val === 'no') return COLORS.errorText;
    return COLORS.warningText;
  };

  const teleheathLabel = (val: string) => {
    if (val === 'yes') return '✓ Generally Accepted';
    if (val === 'no') return '✗ Not Accepted';
    return '~ Case-by-Case';
  };

  if (selected) {
    return (
      <ScrollView style={s.container} contentContainerStyle={s.content}>
        {/* Header */}
        <View style={s.header}>
          <TouchableOpacity onPress={() => setSelected(null)} style={s.backBtn}>
            <Text style={s.backText}>← Back</Text>
          </TouchableOpacity>
          <TouchableOpacity onPress={() => router.push('/(tabs)/dashboard')} style={s.homeBtn}>
            <Text style={s.homeBtnText}>🏠</Text>
          </TouchableOpacity>
        </View>

        <View style={s.stateHero}>
          <Text style={s.stateAbbr}>{selected.abbr}</Text>
          <Text style={s.stateName}>{selected.state}</Text>
          <Text style={s.seaName}>{selected.seaName}</Text>
        </View>

        {/* Quick contact */}
        <View style={s.contactRow}>
          <TouchableOpacity style={s.contactBtn} onPress={() => Linking.openURL(`tel:${selected.seaPhone.replace(/\D/g, '')}`)}>
            <Text style={s.contactBtnIcon}>📞</Text>
            <Text style={s.contactBtnText}>{selected.seaPhone}</Text>
          </TouchableOpacity>
          <TouchableOpacity style={s.contactBtn} onPress={() => Linking.openURL(selected.seaUrl)}>
            <Text style={s.contactBtnIcon}>🌐</Text>
            <Text style={s.contactBtnText}>State Website</Text>
          </TouchableOpacity>
          <TouchableOpacity style={s.contactBtn} onPress={() => Linking.openURL(`mailto:${selected.seaEmail}`)}>
            <Text style={s.contactBtnIcon}>✉️</Text>
            <Text style={s.contactBtnText}>Email</Text>
          </TouchableOpacity>
        </View>

        {/* Telehealth badge */}
        <View style={[s.teleheathBadge, { borderColor: teleheathColor(selected.teleheathEvalAccepted) }]}>
          <Text style={[s.teleheathLabel, { color: teleheathColor(selected.teleheathEvalAccepted) }]}>
            Telehealth Evaluation Acceptance: {teleheathLabel(selected.teleheathEvalAccepted)}
          </Text>
        </View>

        {/* Telehealth Policy Deep Link */}
        <TouchableOpacity
          style={s.telehealthDeepLink}
          onPress={() => router.push('/iep/telehealth-lookup')}
        >
          <Text style={s.telehealthDeepLinkText}>📡 See full telehealth acceptance policy for {selected.state} →</Text>
        </TouchableOpacity>

        {/* Notes callout */}
        {selected.notes && (
          <View style={s.notesBox}>
            <Text style={s.notesIcon}>⚠️</Text>
            <Text style={s.notesText}>{selected.notes}</Text>
          </View>
        )}

        {/* Timelines section */}
        <TouchableOpacity style={s.sectionHeader} onPress={() => toggleSection('timelines')}>
          <Text style={s.sectionTitle}>⏱ Evaluation Timelines</Text>
          <Text style={s.chevron}>{expandedSection === 'timelines' ? '▲' : '▼'}</Text>
        </TouchableOpacity>
        {expandedSection === 'timelines' && (
          <View style={s.sectionBody}>
            {[
              { label: 'Referral Response', value: selected.referralTimeline },
              { label: 'Evaluation Completion', value: selected.evaluationTimeline },
              { label: 'Eligibility Determination', value: selected.eligibilityTimeline },
              { label: 'IEP in Place', value: selected.iepTimeline },
              { label: 'Total Typical Timeline', value: selected.totalTimeline },
            ].map(row => (
              <View key={row.label} style={s.timelineRow}>
                <Text style={s.timelineLabel}>{row.label}</Text>
                <Text style={s.timelineValue}>{row.value}</Text>
              </View>
            ))}
          </View>
        )}

        {/* How to Request */}
        <TouchableOpacity style={s.sectionHeader} onPress={() => toggleSection('request')}>
          <Text style={s.sectionTitle}>📝 How to Request an Evaluation</Text>
          <Text style={s.chevron}>{expandedSection === 'request' ? '▲' : '▼'}</Text>
        </TouchableOpacity>
        {expandedSection === 'request' && (
          <View style={s.sectionBody}>
            <Text style={s.bodyText}>{selected.howToRequest}</Text>
            <View style={s.tipBox}>
              <Text style={s.tipText}>💡 Pro tip: Always send your request in writing — email with read receipt or certified mail. This starts the clock on the district's response timeline.</Text>
            </View>
          </View>
        )}

        {/* Your Rights */}
        <TouchableOpacity style={s.sectionHeader} onPress={() => toggleSection('rights')}>
          <Text style={s.sectionTitle}>⚖️ Your Key Rights in {selected.abbr}</Text>
          <Text style={s.chevron}>{expandedSection === 'rights' ? '▲' : '▼'}</Text>
        </TouchableOpacity>
        {expandedSection === 'rights' && (
          <View style={s.sectionBody}>
            {selected.keyRights.map((right, i) => (
              <View key={i} style={s.rightRow}>
                <Text style={s.rightBullet}>•</Text>
                <Text style={s.rightText}>{right}</Text>
              </View>
            ))}
            <View style={s.tipBox}>
              <Text style={s.tipText}>💡 If the district denies your evaluation request, they must provide a written explanation (Prior Written Notice). You can then file a State Complaint or request a Due Process Hearing.</Text>
            </View>
          </View>
        )}

        {/* Private Eval */}
        <TouchableOpacity style={s.sectionHeader} onPress={() => toggleSection('private')}>
          <Text style={s.sectionTitle}>🏥 Private Evaluation Acceptance</Text>
          <Text style={s.chevron}>{expandedSection === 'private' ? '▲' : '▼'}</Text>
        </TouchableOpacity>
        {expandedSection === 'private' && (
          <View style={s.sectionBody}>
            <View style={[s.privateTag, { backgroundColor: selected.privateEvalAccepted ? '#dcfce7' : '#fee2e2' }]}>
              <Text style={[s.privateTagText, { color: selected.privateEvalAccepted ? '#166534' : '#991b1b' }]}>
                {selected.privateEvalAccepted ? '✓ Private evaluations accepted in ' + selected.abbr : '✗ Private evaluations not automatically accepted'}
              </Text>
            </View>
            <Text style={[s.bodyText, { marginTop: SPACING.sm }]}>
              Under IDEA, you have the right to an Independent Educational Evaluation (IEE) at the district's expense if you disagree with their evaluation. The district can only refuse by filing for due process to defend their evaluation.
            </Text>
            <Text style={[s.bodyText, { marginTop: SPACING.sm }]}>
              Private evaluations from outside providers (like a neuropsychologist or developmental pediatrician) must be considered by the IEP team, though the district is not required to accept all findings.
            </Text>
          </View>
        )}

        {/* Escalation */}
        <TouchableOpacity style={s.sectionHeader} onPress={() => toggleSection('escalation')}>
          <Text style={s.sectionTitle}>🆘 If You Need Help</Text>
          <Text style={s.chevron}>{expandedSection === 'escalation' ? '▲' : '▼'}</Text>
        </TouchableOpacity>
        {expandedSection === 'escalation' && (
          <View style={s.sectionBody}>
            <Text style={s.bodyText}>Your state's Parent Training and Information Center (PTI) provides free advocacy support, training, and guidance. They are federally funded and on your side.</Text>
            <TouchableOpacity style={s.escalationCard} onPress={() => Linking.openURL(selected.escalationUrl)}>
              <Text style={s.escalationName}>{selected.escalationContact}</Text>
              <Text style={s.escalationUrl}>{selected.escalationUrl} →</Text>
            </TouchableOpacity>
            <Text style={[s.bodyText, { marginTop: SPACING.md }]}>
              You can also file a State Complaint directly with {selected.seaName} if you believe the district has violated IDEA requirements.
            </Text>
            <TouchableOpacity style={s.seaBtn} onPress={() => Linking.openURL(selected.seaUrl)}>
              <Text style={s.seaBtnText}>File a State Complaint with {selected.abbr} →</Text>
            </TouchableOpacity>
          </View>
        )}

        {/* Share button */}
        <TouchableOpacity style={s.shareBtn} onPress={handleShare}>
          <Text style={s.shareBtnText}>📤 Share This Info</Text>
        </TouchableOpacity>

        <Text style={s.disclaimer}>Information is based on state IDEA regulations. Always verify current timelines with your district. For legal advice, consult a special education attorney.</Text>
      </ScrollView>
    );
  }

  return (
    <View style={s.container}>
      {/* Header */}
      <View style={s.header}>
        <TouchableOpacity onPress={() => router.back()} style={s.backBtn}>
          <Text style={s.backText}>← Back</Text>
        </TouchableOpacity>
        <Text style={s.headerTitle}>District Lookup</Text>
        <TouchableOpacity onPress={() => router.push('/(tabs)/dashboard')} style={s.homeBtn}>
          <Text style={s.homeBtnText}>🏠</Text>
        </TouchableOpacity>
      </View>

      <View style={s.searchBox}>
        <Text style={s.searchLabel}>Find your state's school evaluation rights, timelines, and contacts</Text>
        <TextInput
          style={s.searchInput}
          value={query}
          onChangeText={setQuery}
          placeholder="Search by state name or abbreviation..."
          placeholderTextColor={COLORS.textLight}
          autoCorrect={false}
          autoCapitalize="words"
        />
      </View>

      {/* Quick state grid */}
      {!query && (
        <ScrollView contentContainerStyle={s.stateGrid}>
          {US_STATES.map(abbr => {
            const d = searchDistricts(abbr)[0];
            if (!d) return null;
            return (
              <TouchableOpacity key={abbr} style={s.stateChip} onPress={() => handleSelect(d)}>
                <Text style={s.stateChipText}>{abbr}</Text>
              </TouchableOpacity>
            );
          })}
        </ScrollView>
      )}

      {/* Search results */}
      {query.length > 0 && (
        <ScrollView contentContainerStyle={{ padding: SPACING.md }}>
          {results.length === 0 ? (
            <Text style={s.noResults}>No states found for "{query}"</Text>
          ) : (
            results.map(d => (
              <TouchableOpacity key={d.abbr} style={s.resultCard} onPress={() => handleSelect(d)}>
                <View style={s.resultLeft}>
                  <Text style={s.resultAbbr}>{d.abbr}</Text>
                  <View>
                    <Text style={s.resultState}>{d.state}</Text>
                    <Text style={s.resultTimeline}>{d.totalTimeline}</Text>
                  </View>
                </View>
                <Text style={s.resultArrow}>→</Text>
              </TouchableOpacity>
            ))
          )}
        </ScrollView>
      )}
    </View>
  );
}

const s = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.bg },
  content: { padding: SPACING.md, paddingBottom: 60 },
  header: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: SPACING.md, paddingTop: Platform.OS === 'ios' ? 56 : SPACING.lg,
    paddingBottom: SPACING.sm, backgroundColor: '#fff',
    borderBottomWidth: 1, borderBottomColor: '#ede9fe',
  },
  backBtn: { padding: 4 },
  backText: { color: COLORS.purple, fontSize: FONT_SIZES.sm, fontWeight: '600' },
  headerTitle: { fontSize: FONT_SIZES.md, fontWeight: '700', color: COLORS.text || '#1e1b4b' },
  homeBtn: { padding: 4 },
  homeBtnText: { fontSize: 20 },

  searchBox: { backgroundColor: '#fff', padding: SPACING.md, borderBottomWidth: 1, borderBottomColor: '#ede9fe' },
  searchLabel: { fontSize: FONT_SIZES.sm, color: COLORS.textLight || '#6b7280', marginBottom: SPACING.sm },
  searchInput: {
    backgroundColor: '#f5f3ff', borderRadius: 10, padding: SPACING.sm,
    fontSize: FONT_SIZES.md, color: COLORS.text || '#1e1b4b',
    borderWidth: 1, borderColor: '#ddd6fe',
  },

  stateGrid: { flexDirection: 'row', flexWrap: 'wrap', padding: SPACING.md, gap: 8 },
  stateChip: {
    backgroundColor: '#ede9fe', borderRadius: 8, paddingHorizontal: 12, paddingVertical: 8,
    minWidth: 52, alignItems: 'center',
  },
  stateChipText: { fontSize: FONT_SIZES.sm, fontWeight: '700', color: COLORS.purple },

  resultCard: {
    backgroundColor: '#fff', borderRadius: 12, padding: SPACING.md,
    marginBottom: SPACING.sm, flexDirection: 'row', alignItems: 'center',
    justifyContent: 'space-between', shadowColor: '#000', shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 2 }, shadowRadius: 4, elevation: 2,
  },
  resultLeft: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  resultAbbr: { fontSize: 20, fontWeight: '800', color: COLORS.purple, width: 36 },
  resultState: { fontSize: FONT_SIZES.md, fontWeight: '600', color: COLORS.text || '#1e1b4b' },
  resultTimeline: { fontSize: FONT_SIZES.xs, color: COLORS.textLight || '#6b7280', marginTop: 2 },
  resultArrow: { fontSize: 18, color: COLORS.purple },
  noResults: { textAlign: 'center', color: COLORS.textLight || '#6b7280', marginTop: 40, fontSize: FONT_SIZES.md },

  // Detail view
  stateHero: { alignItems: 'center', paddingVertical: SPACING.lg, backgroundColor: '#fff', borderRadius: 16, marginBottom: SPACING.md },
  stateAbbr: { fontSize: 48, fontWeight: '900', color: COLORS.purple },
  stateName: { fontSize: FONT_SIZES.xl, fontWeight: '700', color: COLORS.text || '#1e1b4b', marginTop: 4 },
  seaName: { fontSize: FONT_SIZES.xs, color: COLORS.textLight || '#6b7280', textAlign: 'center', marginTop: 4, paddingHorizontal: SPACING.md },

  contactRow: { flexDirection: 'row', gap: 8, marginBottom: SPACING.md },
  contactBtn: {
    flex: 1, backgroundColor: '#fff', borderRadius: 10, padding: SPACING.sm,
    alignItems: 'center', borderWidth: 1, borderColor: '#ede9fe',
  },
  contactBtnIcon: { fontSize: 18, marginBottom: 2 },
  contactBtnText: { fontSize: FONT_SIZES.xs, color: COLORS.purple, fontWeight: '600', textAlign: 'center' },

  teleheathBadge: {
    borderWidth: 1.5, borderRadius: 10, padding: SPACING.sm,
    marginBottom: SPACING.md, backgroundColor: '#fff',
  },
  teleheathLabel: { fontSize: FONT_SIZES.sm, fontWeight: '600', textAlign: 'center' },
  telehealthDeepLink: {
    backgroundColor: '#DCEEFF', borderRadius: 10, padding: SPACING.sm,
    marginBottom: SPACING.md, borderWidth: 1, borderColor: '#A8CFFF',
  },
  telehealthDeepLinkText: { color: '#1A7A8A', fontWeight: '600', fontSize: FONT_SIZES.sm, textAlign: 'center' },

  notesBox: {
    flexDirection: 'row', backgroundColor: '#fffbeb', borderRadius: 10,
    padding: SPACING.sm, marginBottom: SPACING.md, gap: 8,
    borderWidth: 1, borderColor: '#fde68a',
  },
  notesIcon: { fontSize: 16 },
  notesText: { flex: 1, fontSize: FONT_SIZES.sm, color: '#92400e' },

  sectionHeader: {
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
    backgroundColor: '#fff', padding: SPACING.md, borderRadius: 12,
    marginBottom: 2, borderWidth: 1, borderColor: '#ede9fe',
  },
  sectionTitle: { fontSize: FONT_SIZES.md, fontWeight: '700', color: COLORS.text || '#1e1b4b' },
  chevron: { fontSize: 12, color: COLORS.textLight || '#6b7280' },
  sectionBody: {
    backgroundColor: '#faf9ff', padding: SPACING.md, borderRadius: 12,
    marginBottom: SPACING.md, borderWidth: 1, borderColor: '#ede9fe',
  },

  timelineRow: {
    flexDirection: 'row', justifyContent: 'space-between',
    paddingVertical: SPACING.sm, borderBottomWidth: 1, borderBottomColor: '#ede9fe',
  },
  timelineLabel: { fontSize: FONT_SIZES.sm, color: COLORS.textLight || '#6b7280', flex: 1 },
  timelineValue: { fontSize: FONT_SIZES.sm, fontWeight: '600', color: COLORS.text || '#1e1b4b', flex: 1, textAlign: 'right' },

  bodyText: { fontSize: FONT_SIZES.sm, color: COLORS.text || '#1e1b4b', lineHeight: 20 },
  tipBox: {
    backgroundColor: '#ede9fe', borderRadius: 8, padding: SPACING.sm, marginTop: SPACING.sm,
  },
  tipText: { fontSize: FONT_SIZES.xs, color: COLORS.purple, lineHeight: 18 },

  rightRow: { flexDirection: 'row', gap: 8, marginBottom: SPACING.sm },
  rightBullet: { fontSize: FONT_SIZES.sm, color: COLORS.purple, marginTop: 2 },
  rightText: { flex: 1, fontSize: FONT_SIZES.sm, color: COLORS.text || '#1e1b4b', lineHeight: 20 },

  privateTag: { borderRadius: 8, padding: SPACING.sm },
  privateTagText: { fontSize: FONT_SIZES.sm, fontWeight: '600' },

  escalationCard: {
    backgroundColor: '#ede9fe', borderRadius: 10, padding: SPACING.md, marginTop: SPACING.sm,
  },
  escalationName: { fontSize: FONT_SIZES.md, fontWeight: '700', color: COLORS.purple },
  escalationUrl: { fontSize: FONT_SIZES.xs, color: COLORS.purple, marginTop: 2 },

  seaBtn: {
    backgroundColor: COLORS.purple, borderRadius: 10,
    padding: SPACING.sm, marginTop: SPACING.sm, alignItems: 'center',
  },
  seaBtnText: { color: '#fff', fontWeight: '700', fontSize: FONT_SIZES.sm },

  shareBtn: {
    backgroundColor: COLORS.purple, borderRadius: 14,
    padding: SPACING.md, alignItems: 'center', marginTop: SPACING.lg, marginBottom: SPACING.md,
  },
  shareBtnText: { color: '#fff', fontWeight: '700', fontSize: FONT_SIZES.md },

  disclaimer: { fontSize: FONT_SIZES.xs, color: COLORS.textLight || '#9ca3af', textAlign: 'center', lineHeight: 16 },
});
